// <auto-generated />
using System;
using GenerateurDOE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenerateurDOE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918122846_UpdatePageGardeTemplateIntegration")]
    partial class UpdatePageGardeTemplateIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentGenereFicheTechnique", b =>
                {
                    b.Property<int>("DocumentGenereId")
                        .HasColumnType("int");

                    b.Property<int>("FicheTechniqueId")
                        .HasColumnType("int");

                    b.HasKey("DocumentGenereId", "FicheTechniqueId");

                    b.HasIndex("FicheTechniqueId");

                    b.ToTable("DocumentGenereFicheTechniques", (string)null);
                });

            modelBuilder.Entity("GenerateurDOE.Models.Chantier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("EstArchive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MaitreOeuvre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaitreOuvrage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomProjet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Chantiers");
                });

            modelBuilder.Entity("GenerateurDOE.Models.DocumentGenere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChantierId")
                        .HasColumnType("int");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("EnCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("FormatExport")
                        .HasColumnType("int");

                    b.Property<bool>("IncludePageDeGarde")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeTableMatieres")
                        .HasColumnType("bit");

                    b.Property<string>("IntituleLot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PageGardeTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Parametres")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TypeDocument")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChantierId");

                    b.HasIndex("PageGardeTemplateId");

                    b.ToTable("DocumentsGeneres");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FTConteneur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AfficherTableauRecapitulatif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DocumentGenereId")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentGenereId")
                        .IsUnique();

                    b.ToTable("FTConteneurs");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FTElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FTConteneursId")
                        .HasColumnType("int");

                    b.Property<int>("FicheTechniqueId")
                        .HasColumnType("int");

                    b.Property<int?>("ImportPDFId")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroPage")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("PositionMarche")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FTConteneursId");

                    b.HasIndex("FicheTechniqueId");

                    b.HasIndex("ImportPDFId");

                    b.ToTable("FTElements");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FicheTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChantierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NomFabricant")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeProduit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TypeProduitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChantierId");

                    b.HasIndex("TypeProduitId");

                    b.ToTable("FichesTechniques");
                });

            modelBuilder.Entity("GenerateurDOE.Models.ImageMethode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateImport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MethodeId")
                        .HasColumnType("int");

                    b.Property<string>("NomFichierOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrdreAffichage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MethodeId");

                    b.ToTable("ImagesMethode");
                });

            modelBuilder.Entity("GenerateurDOE.Models.ImportPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateImport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FicheTechniqueId")
                        .HasColumnType("int");

                    b.Property<string>("NomFichierOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TailleFichier")
                        .HasColumnType("bigint");

                    b.Property<int>("TypeDocumentImportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FicheTechniqueId");

                    b.HasIndex("TypeDocumentImportId");

                    b.ToTable("ImportsPDF");
                });

            modelBuilder.Entity("GenerateurDOE.Models.Methode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdreAffichage")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Methodes");
                });

            modelBuilder.Entity("GenerateurDOE.Models.PageGardeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenuHtml")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenuJson")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstParDefaut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("PageGardeTemplates");
                });

            modelBuilder.Entity("GenerateurDOE.Models.SectionConteneur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DocumentGenereId")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeSectionId");

                    b.HasIndex("DocumentGenereId", "TypeSectionId")
                        .IsUnique()
                        .HasDatabaseName("IX_SectionConteneur_DocumentGenere_TypeSection");

                    b.ToTable("SectionsConteneurs");
                });

            modelBuilder.Entity("GenerateurDOE.Models.SectionConteneurItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<int>("SectionConteneursId")
                        .HasColumnType("int");

                    b.Property<int>("SectionLibreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionLibreId");

                    b.HasIndex("SectionConteneursId", "SectionLibreId")
                        .IsUnique();

                    b.ToTable("SectionConteneurItems");
                });

            modelBuilder.Entity("GenerateurDOE.Models.SectionLibre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenuHtml")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenuJson")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeSectionId");

                    b.ToTable("SectionsLibres");
                });

            modelBuilder.Entity("GenerateurDOE.Models.TypeDocumentImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TypesDocuments");
                });

            modelBuilder.Entity("GenerateurDOE.Models.TypeProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TypesProduits");
                });

            modelBuilder.Entity("GenerateurDOE.Models.TypeSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TypesSections");
                });

            modelBuilder.Entity("DocumentGenereFicheTechnique", b =>
                {
                    b.HasOne("GenerateurDOE.Models.DocumentGenere", null)
                        .WithMany()
                        .HasForeignKey("DocumentGenereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenerateurDOE.Models.FicheTechnique", null)
                        .WithMany()
                        .HasForeignKey("FicheTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenerateurDOE.Models.DocumentGenere", b =>
                {
                    b.HasOne("GenerateurDOE.Models.Chantier", "Chantier")
                        .WithMany("DocumentsGeneres")
                        .HasForeignKey("ChantierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenerateurDOE.Models.PageGardeTemplate", "PageGardeTemplate")
                        .WithMany()
                        .HasForeignKey("PageGardeTemplateId");

                    b.Navigation("Chantier");

                    b.Navigation("PageGardeTemplate");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FTConteneur", b =>
                {
                    b.HasOne("GenerateurDOE.Models.DocumentGenere", "DocumentGenere")
                        .WithOne("FTConteneur")
                        .HasForeignKey("GenerateurDOE.Models.FTConteneur", "DocumentGenereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentGenere");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FTElement", b =>
                {
                    b.HasOne("GenerateurDOE.Models.FTConteneur", "FTConteneur")
                        .WithMany("Elements")
                        .HasForeignKey("FTConteneursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenerateurDOE.Models.FicheTechnique", "FicheTechnique")
                        .WithMany()
                        .HasForeignKey("FicheTechniqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenerateurDOE.Models.ImportPDF", "ImportPDF")
                        .WithMany()
                        .HasForeignKey("ImportPDFId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FTConteneur");

                    b.Navigation("FicheTechnique");

                    b.Navigation("ImportPDF");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FicheTechnique", b =>
                {
                    b.HasOne("GenerateurDOE.Models.Chantier", null)
                        .WithMany("FichesTechniques")
                        .HasForeignKey("ChantierId");

                    b.HasOne("GenerateurDOE.Models.TypeProduit", null)
                        .WithMany("FichesTechniques")
                        .HasForeignKey("TypeProduitId");
                });

            modelBuilder.Entity("GenerateurDOE.Models.ImageMethode", b =>
                {
                    b.HasOne("GenerateurDOE.Models.Methode", "Methode")
                        .WithMany("Images")
                        .HasForeignKey("MethodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Methode");
                });

            modelBuilder.Entity("GenerateurDOE.Models.ImportPDF", b =>
                {
                    b.HasOne("GenerateurDOE.Models.FicheTechnique", "FicheTechnique")
                        .WithMany("ImportsPDF")
                        .HasForeignKey("FicheTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenerateurDOE.Models.TypeDocumentImport", "TypeDocumentImport")
                        .WithMany()
                        .HasForeignKey("TypeDocumentImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FicheTechnique");

                    b.Navigation("TypeDocumentImport");
                });

            modelBuilder.Entity("GenerateurDOE.Models.SectionConteneur", b =>
                {
                    b.HasOne("GenerateurDOE.Models.DocumentGenere", "DocumentGenere")
                        .WithMany("SectionsConteneurs")
                        .HasForeignKey("DocumentGenereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenerateurDOE.Models.TypeSection", "TypeSection")
                        .WithMany()
                        .HasForeignKey("TypeSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentGenere");

                    b.Navigation("TypeSection");
                });

            modelBuilder.Entity("GenerateurDOE.Models.SectionConteneurItem", b =>
                {
                    b.HasOne("GenerateurDOE.Models.SectionConteneur", "SectionConteneur")
                        .WithMany("Items")
                        .HasForeignKey("SectionConteneursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenerateurDOE.Models.SectionLibre", "SectionLibre")
                        .WithMany()
                        .HasForeignKey("SectionLibreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionConteneur");

                    b.Navigation("SectionLibre");
                });

            modelBuilder.Entity("GenerateurDOE.Models.SectionLibre", b =>
                {
                    b.HasOne("GenerateurDOE.Models.TypeSection", "TypeSection")
                        .WithMany("SectionsLibres")
                        .HasForeignKey("TypeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeSection");
                });

            modelBuilder.Entity("GenerateurDOE.Models.Chantier", b =>
                {
                    b.Navigation("DocumentsGeneres");

                    b.Navigation("FichesTechniques");
                });

            modelBuilder.Entity("GenerateurDOE.Models.DocumentGenere", b =>
                {
                    b.Navigation("FTConteneur");

                    b.Navigation("SectionsConteneurs");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FTConteneur", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("GenerateurDOE.Models.FicheTechnique", b =>
                {
                    b.Navigation("ImportsPDF");
                });

            modelBuilder.Entity("GenerateurDOE.Models.Methode", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("GenerateurDOE.Models.SectionConteneur", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GenerateurDOE.Models.TypeProduit", b =>
                {
                    b.Navigation("FichesTechniques");
                });

            modelBuilder.Entity("GenerateurDOE.Models.TypeSection", b =>
                {
                    b.Navigation("SectionsLibres");
                });
#pragma warning restore 612, 618
        }
    }
}
